name: Revisar Archivos JSON

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate JSON files
      run: |
        for file in $(find . -name "*.json"); do
          echo "Validating $file"
          jq empty "$file" || exit 1
        done
